
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BanDetails` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BanDetails
 * 
 */
export type BanDetailsModel = runtime.Types.Result.DefaultSelection<Prisma.$BanDetailsPayload>

export type AggregateBanDetails = {
  _count: BanDetailsCountAggregateOutputType | null
  _min: BanDetailsMinAggregateOutputType | null
  _max: BanDetailsMaxAggregateOutputType | null
}

export type BanDetailsMinAggregateOutputType = {
  id: string | null
  userId: string | null
  isBanned: boolean | null
  bannedBy: string | null
  banReason: string | null
  banUntil: Date | null
  createdAt: Date | null
}

export type BanDetailsMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  isBanned: boolean | null
  bannedBy: string | null
  banReason: string | null
  banUntil: Date | null
  createdAt: Date | null
}

export type BanDetailsCountAggregateOutputType = {
  id: number
  userId: number
  isBanned: number
  bannedBy: number
  banReason: number
  banUntil: number
  createdAt: number
  _all: number
}


export type BanDetailsMinAggregateInputType = {
  id?: true
  userId?: true
  isBanned?: true
  bannedBy?: true
  banReason?: true
  banUntil?: true
  createdAt?: true
}

export type BanDetailsMaxAggregateInputType = {
  id?: true
  userId?: true
  isBanned?: true
  bannedBy?: true
  banReason?: true
  banUntil?: true
  createdAt?: true
}

export type BanDetailsCountAggregateInputType = {
  id?: true
  userId?: true
  isBanned?: true
  bannedBy?: true
  banReason?: true
  banUntil?: true
  createdAt?: true
  _all?: true
}

export type BanDetailsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BanDetails to aggregate.
   */
  where?: Prisma.BanDetailsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BanDetails to fetch.
   */
  orderBy?: Prisma.BanDetailsOrderByWithRelationInput | Prisma.BanDetailsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BanDetailsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BanDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BanDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BanDetails
  **/
  _count?: true | BanDetailsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BanDetailsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BanDetailsMaxAggregateInputType
}

export type GetBanDetailsAggregateType<T extends BanDetailsAggregateArgs> = {
      [P in keyof T & keyof AggregateBanDetails]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBanDetails[P]>
    : Prisma.GetScalarType<T[P], AggregateBanDetails[P]>
}




export type BanDetailsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BanDetailsWhereInput
  orderBy?: Prisma.BanDetailsOrderByWithAggregationInput | Prisma.BanDetailsOrderByWithAggregationInput[]
  by: Prisma.BanDetailsScalarFieldEnum[] | Prisma.BanDetailsScalarFieldEnum
  having?: Prisma.BanDetailsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BanDetailsCountAggregateInputType | true
  _min?: BanDetailsMinAggregateInputType
  _max?: BanDetailsMaxAggregateInputType
}

export type BanDetailsGroupByOutputType = {
  id: string
  userId: string
  isBanned: boolean
  bannedBy: string
  banReason: string | null
  banUntil: Date | null
  createdAt: Date
  _count: BanDetailsCountAggregateOutputType | null
  _min: BanDetailsMinAggregateOutputType | null
  _max: BanDetailsMaxAggregateOutputType | null
}

type GetBanDetailsGroupByPayload<T extends BanDetailsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BanDetailsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BanDetailsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BanDetailsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BanDetailsGroupByOutputType[P]>
      }
    >
  >



export type BanDetailsWhereInput = {
  AND?: Prisma.BanDetailsWhereInput | Prisma.BanDetailsWhereInput[]
  OR?: Prisma.BanDetailsWhereInput[]
  NOT?: Prisma.BanDetailsWhereInput | Prisma.BanDetailsWhereInput[]
  id?: Prisma.StringFilter<"BanDetails"> | string
  userId?: Prisma.StringFilter<"BanDetails"> | string
  isBanned?: Prisma.BoolFilter<"BanDetails"> | boolean
  bannedBy?: Prisma.StringFilter<"BanDetails"> | string
  banReason?: Prisma.StringNullableFilter<"BanDetails"> | string | null
  banUntil?: Prisma.DateTimeNullableFilter<"BanDetails"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"BanDetails"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type BanDetailsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  isBanned?: Prisma.SortOrder
  bannedBy?: Prisma.SortOrder
  banReason?: Prisma.SortOrderInput | Prisma.SortOrder
  banUntil?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type BanDetailsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BanDetailsWhereInput | Prisma.BanDetailsWhereInput[]
  OR?: Prisma.BanDetailsWhereInput[]
  NOT?: Prisma.BanDetailsWhereInput | Prisma.BanDetailsWhereInput[]
  userId?: Prisma.StringFilter<"BanDetails"> | string
  isBanned?: Prisma.BoolFilter<"BanDetails"> | boolean
  bannedBy?: Prisma.StringFilter<"BanDetails"> | string
  banReason?: Prisma.StringNullableFilter<"BanDetails"> | string | null
  banUntil?: Prisma.DateTimeNullableFilter<"BanDetails"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"BanDetails"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type BanDetailsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  isBanned?: Prisma.SortOrder
  bannedBy?: Prisma.SortOrder
  banReason?: Prisma.SortOrderInput | Prisma.SortOrder
  banUntil?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.BanDetailsCountOrderByAggregateInput
  _max?: Prisma.BanDetailsMaxOrderByAggregateInput
  _min?: Prisma.BanDetailsMinOrderByAggregateInput
}

export type BanDetailsScalarWhereWithAggregatesInput = {
  AND?: Prisma.BanDetailsScalarWhereWithAggregatesInput | Prisma.BanDetailsScalarWhereWithAggregatesInput[]
  OR?: Prisma.BanDetailsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BanDetailsScalarWhereWithAggregatesInput | Prisma.BanDetailsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BanDetails"> | string
  userId?: Prisma.StringWithAggregatesFilter<"BanDetails"> | string
  isBanned?: Prisma.BoolWithAggregatesFilter<"BanDetails"> | boolean
  bannedBy?: Prisma.StringWithAggregatesFilter<"BanDetails"> | string
  banReason?: Prisma.StringNullableWithAggregatesFilter<"BanDetails"> | string | null
  banUntil?: Prisma.DateTimeNullableWithAggregatesFilter<"BanDetails"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BanDetails"> | Date | string
}

export type BanDetailsCreateInput = {
  id?: string
  isBanned?: boolean
  bannedBy: string
  banReason?: string | null
  banUntil?: Date | string | null
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutBanDetailsInput
}

export type BanDetailsUncheckedCreateInput = {
  id?: string
  userId: string
  isBanned?: boolean
  bannedBy: string
  banReason?: string | null
  banUntil?: Date | string | null
  createdAt?: Date | string
}

export type BanDetailsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  bannedBy?: Prisma.StringFieldUpdateOperationsInput | string
  banReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutBanDetailsNestedInput
}

export type BanDetailsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  bannedBy?: Prisma.StringFieldUpdateOperationsInput | string
  banReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BanDetailsCreateManyInput = {
  id?: string
  userId: string
  isBanned?: boolean
  bannedBy: string
  banReason?: string | null
  banUntil?: Date | string | null
  createdAt?: Date | string
}

export type BanDetailsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  bannedBy?: Prisma.StringFieldUpdateOperationsInput | string
  banReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BanDetailsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  bannedBy?: Prisma.StringFieldUpdateOperationsInput | string
  banReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BanDetailsListRelationFilter = {
  every?: Prisma.BanDetailsWhereInput
  some?: Prisma.BanDetailsWhereInput
  none?: Prisma.BanDetailsWhereInput
}

export type BanDetailsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BanDetailsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  isBanned?: Prisma.SortOrder
  bannedBy?: Prisma.SortOrder
  banReason?: Prisma.SortOrder
  banUntil?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BanDetailsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  isBanned?: Prisma.SortOrder
  bannedBy?: Prisma.SortOrder
  banReason?: Prisma.SortOrder
  banUntil?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BanDetailsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  isBanned?: Prisma.SortOrder
  bannedBy?: Prisma.SortOrder
  banReason?: Prisma.SortOrder
  banUntil?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BanDetailsCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BanDetailsCreateWithoutUserInput, Prisma.BanDetailsUncheckedCreateWithoutUserInput> | Prisma.BanDetailsCreateWithoutUserInput[] | Prisma.BanDetailsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BanDetailsCreateOrConnectWithoutUserInput | Prisma.BanDetailsCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BanDetailsCreateManyUserInputEnvelope
  connect?: Prisma.BanDetailsWhereUniqueInput | Prisma.BanDetailsWhereUniqueInput[]
}

export type BanDetailsUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BanDetailsCreateWithoutUserInput, Prisma.BanDetailsUncheckedCreateWithoutUserInput> | Prisma.BanDetailsCreateWithoutUserInput[] | Prisma.BanDetailsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BanDetailsCreateOrConnectWithoutUserInput | Prisma.BanDetailsCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BanDetailsCreateManyUserInputEnvelope
  connect?: Prisma.BanDetailsWhereUniqueInput | Prisma.BanDetailsWhereUniqueInput[]
}

export type BanDetailsUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BanDetailsCreateWithoutUserInput, Prisma.BanDetailsUncheckedCreateWithoutUserInput> | Prisma.BanDetailsCreateWithoutUserInput[] | Prisma.BanDetailsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BanDetailsCreateOrConnectWithoutUserInput | Prisma.BanDetailsCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BanDetailsUpsertWithWhereUniqueWithoutUserInput | Prisma.BanDetailsUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BanDetailsCreateManyUserInputEnvelope
  set?: Prisma.BanDetailsWhereUniqueInput | Prisma.BanDetailsWhereUniqueInput[]
  disconnect?: Prisma.BanDetailsWhereUniqueInput | Prisma.BanDetailsWhereUniqueInput[]
  delete?: Prisma.BanDetailsWhereUniqueInput | Prisma.BanDetailsWhereUniqueInput[]
  connect?: Prisma.BanDetailsWhereUniqueInput | Prisma.BanDetailsWhereUniqueInput[]
  update?: Prisma.BanDetailsUpdateWithWhereUniqueWithoutUserInput | Prisma.BanDetailsUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BanDetailsUpdateManyWithWhereWithoutUserInput | Prisma.BanDetailsUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BanDetailsScalarWhereInput | Prisma.BanDetailsScalarWhereInput[]
}

export type BanDetailsUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BanDetailsCreateWithoutUserInput, Prisma.BanDetailsUncheckedCreateWithoutUserInput> | Prisma.BanDetailsCreateWithoutUserInput[] | Prisma.BanDetailsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BanDetailsCreateOrConnectWithoutUserInput | Prisma.BanDetailsCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BanDetailsUpsertWithWhereUniqueWithoutUserInput | Prisma.BanDetailsUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BanDetailsCreateManyUserInputEnvelope
  set?: Prisma.BanDetailsWhereUniqueInput | Prisma.BanDetailsWhereUniqueInput[]
  disconnect?: Prisma.BanDetailsWhereUniqueInput | Prisma.BanDetailsWhereUniqueInput[]
  delete?: Prisma.BanDetailsWhereUniqueInput | Prisma.BanDetailsWhereUniqueInput[]
  connect?: Prisma.BanDetailsWhereUniqueInput | Prisma.BanDetailsWhereUniqueInput[]
  update?: Prisma.BanDetailsUpdateWithWhereUniqueWithoutUserInput | Prisma.BanDetailsUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BanDetailsUpdateManyWithWhereWithoutUserInput | Prisma.BanDetailsUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BanDetailsScalarWhereInput | Prisma.BanDetailsScalarWhereInput[]
}

export type BanDetailsCreateWithoutUserInput = {
  id?: string
  isBanned?: boolean
  bannedBy: string
  banReason?: string | null
  banUntil?: Date | string | null
  createdAt?: Date | string
}

export type BanDetailsUncheckedCreateWithoutUserInput = {
  id?: string
  isBanned?: boolean
  bannedBy: string
  banReason?: string | null
  banUntil?: Date | string | null
  createdAt?: Date | string
}

export type BanDetailsCreateOrConnectWithoutUserInput = {
  where: Prisma.BanDetailsWhereUniqueInput
  create: Prisma.XOR<Prisma.BanDetailsCreateWithoutUserInput, Prisma.BanDetailsUncheckedCreateWithoutUserInput>
}

export type BanDetailsCreateManyUserInputEnvelope = {
  data: Prisma.BanDetailsCreateManyUserInput | Prisma.BanDetailsCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type BanDetailsUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.BanDetailsWhereUniqueInput
  update: Prisma.XOR<Prisma.BanDetailsUpdateWithoutUserInput, Prisma.BanDetailsUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.BanDetailsCreateWithoutUserInput, Prisma.BanDetailsUncheckedCreateWithoutUserInput>
}

export type BanDetailsUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.BanDetailsWhereUniqueInput
  data: Prisma.XOR<Prisma.BanDetailsUpdateWithoutUserInput, Prisma.BanDetailsUncheckedUpdateWithoutUserInput>
}

export type BanDetailsUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.BanDetailsScalarWhereInput
  data: Prisma.XOR<Prisma.BanDetailsUpdateManyMutationInput, Prisma.BanDetailsUncheckedUpdateManyWithoutUserInput>
}

export type BanDetailsScalarWhereInput = {
  AND?: Prisma.BanDetailsScalarWhereInput | Prisma.BanDetailsScalarWhereInput[]
  OR?: Prisma.BanDetailsScalarWhereInput[]
  NOT?: Prisma.BanDetailsScalarWhereInput | Prisma.BanDetailsScalarWhereInput[]
  id?: Prisma.StringFilter<"BanDetails"> | string
  userId?: Prisma.StringFilter<"BanDetails"> | string
  isBanned?: Prisma.BoolFilter<"BanDetails"> | boolean
  bannedBy?: Prisma.StringFilter<"BanDetails"> | string
  banReason?: Prisma.StringNullableFilter<"BanDetails"> | string | null
  banUntil?: Prisma.DateTimeNullableFilter<"BanDetails"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"BanDetails"> | Date | string
}

export type BanDetailsCreateManyUserInput = {
  id?: string
  isBanned?: boolean
  bannedBy: string
  banReason?: string | null
  banUntil?: Date | string | null
  createdAt?: Date | string
}

export type BanDetailsUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  bannedBy?: Prisma.StringFieldUpdateOperationsInput | string
  banReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BanDetailsUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  bannedBy?: Prisma.StringFieldUpdateOperationsInput | string
  banReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BanDetailsUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  bannedBy?: Prisma.StringFieldUpdateOperationsInput | string
  banReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type BanDetailsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  isBanned?: boolean
  bannedBy?: boolean
  banReason?: boolean
  banUntil?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["banDetails"]>

export type BanDetailsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  isBanned?: boolean
  bannedBy?: boolean
  banReason?: boolean
  banUntil?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["banDetails"]>

export type BanDetailsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  isBanned?: boolean
  bannedBy?: boolean
  banReason?: boolean
  banUntil?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["banDetails"]>

export type BanDetailsSelectScalar = {
  id?: boolean
  userId?: boolean
  isBanned?: boolean
  bannedBy?: boolean
  banReason?: boolean
  banUntil?: boolean
  createdAt?: boolean
}

export type BanDetailsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "isBanned" | "bannedBy" | "banReason" | "banUntil" | "createdAt", ExtArgs["result"]["banDetails"]>
export type BanDetailsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type BanDetailsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type BanDetailsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $BanDetailsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BanDetails"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    isBanned: boolean
    bannedBy: string
    banReason: string | null
    banUntil: Date | null
    createdAt: Date
  }, ExtArgs["result"]["banDetails"]>
  composites: {}
}

export type BanDetailsGetPayload<S extends boolean | null | undefined | BanDetailsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BanDetailsPayload, S>

export type BanDetailsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BanDetailsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BanDetailsCountAggregateInputType | true
  }

export interface BanDetailsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BanDetails'], meta: { name: 'BanDetails' } }
  /**
   * Find zero or one BanDetails that matches the filter.
   * @param {BanDetailsFindUniqueArgs} args - Arguments to find a BanDetails
   * @example
   * // Get one BanDetails
   * const banDetails = await prisma.banDetails.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BanDetailsFindUniqueArgs>(args: Prisma.SelectSubset<T, BanDetailsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BanDetailsClient<runtime.Types.Result.GetResult<Prisma.$BanDetailsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BanDetails that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BanDetailsFindUniqueOrThrowArgs} args - Arguments to find a BanDetails
   * @example
   * // Get one BanDetails
   * const banDetails = await prisma.banDetails.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BanDetailsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BanDetailsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BanDetailsClient<runtime.Types.Result.GetResult<Prisma.$BanDetailsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BanDetails that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BanDetailsFindFirstArgs} args - Arguments to find a BanDetails
   * @example
   * // Get one BanDetails
   * const banDetails = await prisma.banDetails.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BanDetailsFindFirstArgs>(args?: Prisma.SelectSubset<T, BanDetailsFindFirstArgs<ExtArgs>>): Prisma.Prisma__BanDetailsClient<runtime.Types.Result.GetResult<Prisma.$BanDetailsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BanDetails that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BanDetailsFindFirstOrThrowArgs} args - Arguments to find a BanDetails
   * @example
   * // Get one BanDetails
   * const banDetails = await prisma.banDetails.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BanDetailsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BanDetailsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BanDetailsClient<runtime.Types.Result.GetResult<Prisma.$BanDetailsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BanDetails that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BanDetailsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BanDetails
   * const banDetails = await prisma.banDetails.findMany()
   * 
   * // Get first 10 BanDetails
   * const banDetails = await prisma.banDetails.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const banDetailsWithIdOnly = await prisma.banDetails.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BanDetailsFindManyArgs>(args?: Prisma.SelectSubset<T, BanDetailsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BanDetailsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BanDetails.
   * @param {BanDetailsCreateArgs} args - Arguments to create a BanDetails.
   * @example
   * // Create one BanDetails
   * const BanDetails = await prisma.banDetails.create({
   *   data: {
   *     // ... data to create a BanDetails
   *   }
   * })
   * 
   */
  create<T extends BanDetailsCreateArgs>(args: Prisma.SelectSubset<T, BanDetailsCreateArgs<ExtArgs>>): Prisma.Prisma__BanDetailsClient<runtime.Types.Result.GetResult<Prisma.$BanDetailsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BanDetails.
   * @param {BanDetailsCreateManyArgs} args - Arguments to create many BanDetails.
   * @example
   * // Create many BanDetails
   * const banDetails = await prisma.banDetails.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BanDetailsCreateManyArgs>(args?: Prisma.SelectSubset<T, BanDetailsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BanDetails and returns the data saved in the database.
   * @param {BanDetailsCreateManyAndReturnArgs} args - Arguments to create many BanDetails.
   * @example
   * // Create many BanDetails
   * const banDetails = await prisma.banDetails.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BanDetails and only return the `id`
   * const banDetailsWithIdOnly = await prisma.banDetails.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BanDetailsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BanDetailsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BanDetailsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BanDetails.
   * @param {BanDetailsDeleteArgs} args - Arguments to delete one BanDetails.
   * @example
   * // Delete one BanDetails
   * const BanDetails = await prisma.banDetails.delete({
   *   where: {
   *     // ... filter to delete one BanDetails
   *   }
   * })
   * 
   */
  delete<T extends BanDetailsDeleteArgs>(args: Prisma.SelectSubset<T, BanDetailsDeleteArgs<ExtArgs>>): Prisma.Prisma__BanDetailsClient<runtime.Types.Result.GetResult<Prisma.$BanDetailsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BanDetails.
   * @param {BanDetailsUpdateArgs} args - Arguments to update one BanDetails.
   * @example
   * // Update one BanDetails
   * const banDetails = await prisma.banDetails.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BanDetailsUpdateArgs>(args: Prisma.SelectSubset<T, BanDetailsUpdateArgs<ExtArgs>>): Prisma.Prisma__BanDetailsClient<runtime.Types.Result.GetResult<Prisma.$BanDetailsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BanDetails.
   * @param {BanDetailsDeleteManyArgs} args - Arguments to filter BanDetails to delete.
   * @example
   * // Delete a few BanDetails
   * const { count } = await prisma.banDetails.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BanDetailsDeleteManyArgs>(args?: Prisma.SelectSubset<T, BanDetailsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BanDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BanDetailsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BanDetails
   * const banDetails = await prisma.banDetails.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BanDetailsUpdateManyArgs>(args: Prisma.SelectSubset<T, BanDetailsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BanDetails and returns the data updated in the database.
   * @param {BanDetailsUpdateManyAndReturnArgs} args - Arguments to update many BanDetails.
   * @example
   * // Update many BanDetails
   * const banDetails = await prisma.banDetails.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BanDetails and only return the `id`
   * const banDetailsWithIdOnly = await prisma.banDetails.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BanDetailsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BanDetailsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BanDetailsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BanDetails.
   * @param {BanDetailsUpsertArgs} args - Arguments to update or create a BanDetails.
   * @example
   * // Update or create a BanDetails
   * const banDetails = await prisma.banDetails.upsert({
   *   create: {
   *     // ... data to create a BanDetails
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BanDetails we want to update
   *   }
   * })
   */
  upsert<T extends BanDetailsUpsertArgs>(args: Prisma.SelectSubset<T, BanDetailsUpsertArgs<ExtArgs>>): Prisma.Prisma__BanDetailsClient<runtime.Types.Result.GetResult<Prisma.$BanDetailsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BanDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BanDetailsCountArgs} args - Arguments to filter BanDetails to count.
   * @example
   * // Count the number of BanDetails
   * const count = await prisma.banDetails.count({
   *   where: {
   *     // ... the filter for the BanDetails we want to count
   *   }
   * })
  **/
  count<T extends BanDetailsCountArgs>(
    args?: Prisma.Subset<T, BanDetailsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BanDetailsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BanDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BanDetailsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BanDetailsAggregateArgs>(args: Prisma.Subset<T, BanDetailsAggregateArgs>): Prisma.PrismaPromise<GetBanDetailsAggregateType<T>>

  /**
   * Group by BanDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BanDetailsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BanDetailsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BanDetailsGroupByArgs['orderBy'] }
      : { orderBy?: BanDetailsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BanDetailsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBanDetailsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BanDetails model
 */
readonly fields: BanDetailsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BanDetails.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BanDetailsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BanDetails model
 */
export interface BanDetailsFieldRefs {
  readonly id: Prisma.FieldRef<"BanDetails", 'String'>
  readonly userId: Prisma.FieldRef<"BanDetails", 'String'>
  readonly isBanned: Prisma.FieldRef<"BanDetails", 'Boolean'>
  readonly bannedBy: Prisma.FieldRef<"BanDetails", 'String'>
  readonly banReason: Prisma.FieldRef<"BanDetails", 'String'>
  readonly banUntil: Prisma.FieldRef<"BanDetails", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"BanDetails", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BanDetails findUnique
 */
export type BanDetailsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BanDetails
   */
  select?: Prisma.BanDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BanDetails
   */
  omit?: Prisma.BanDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BanDetailsInclude<ExtArgs> | null
  /**
   * Filter, which BanDetails to fetch.
   */
  where: Prisma.BanDetailsWhereUniqueInput
}

/**
 * BanDetails findUniqueOrThrow
 */
export type BanDetailsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BanDetails
   */
  select?: Prisma.BanDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BanDetails
   */
  omit?: Prisma.BanDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BanDetailsInclude<ExtArgs> | null
  /**
   * Filter, which BanDetails to fetch.
   */
  where: Prisma.BanDetailsWhereUniqueInput
}

/**
 * BanDetails findFirst
 */
export type BanDetailsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BanDetails
   */
  select?: Prisma.BanDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BanDetails
   */
  omit?: Prisma.BanDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BanDetailsInclude<ExtArgs> | null
  /**
   * Filter, which BanDetails to fetch.
   */
  where?: Prisma.BanDetailsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BanDetails to fetch.
   */
  orderBy?: Prisma.BanDetailsOrderByWithRelationInput | Prisma.BanDetailsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BanDetails.
   */
  cursor?: Prisma.BanDetailsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BanDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BanDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BanDetails.
   */
  distinct?: Prisma.BanDetailsScalarFieldEnum | Prisma.BanDetailsScalarFieldEnum[]
}

/**
 * BanDetails findFirstOrThrow
 */
export type BanDetailsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BanDetails
   */
  select?: Prisma.BanDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BanDetails
   */
  omit?: Prisma.BanDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BanDetailsInclude<ExtArgs> | null
  /**
   * Filter, which BanDetails to fetch.
   */
  where?: Prisma.BanDetailsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BanDetails to fetch.
   */
  orderBy?: Prisma.BanDetailsOrderByWithRelationInput | Prisma.BanDetailsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BanDetails.
   */
  cursor?: Prisma.BanDetailsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BanDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BanDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BanDetails.
   */
  distinct?: Prisma.BanDetailsScalarFieldEnum | Prisma.BanDetailsScalarFieldEnum[]
}

/**
 * BanDetails findMany
 */
export type BanDetailsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BanDetails
   */
  select?: Prisma.BanDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BanDetails
   */
  omit?: Prisma.BanDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BanDetailsInclude<ExtArgs> | null
  /**
   * Filter, which BanDetails to fetch.
   */
  where?: Prisma.BanDetailsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BanDetails to fetch.
   */
  orderBy?: Prisma.BanDetailsOrderByWithRelationInput | Prisma.BanDetailsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BanDetails.
   */
  cursor?: Prisma.BanDetailsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BanDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BanDetails.
   */
  skip?: number
  distinct?: Prisma.BanDetailsScalarFieldEnum | Prisma.BanDetailsScalarFieldEnum[]
}

/**
 * BanDetails create
 */
export type BanDetailsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BanDetails
   */
  select?: Prisma.BanDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BanDetails
   */
  omit?: Prisma.BanDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BanDetailsInclude<ExtArgs> | null
  /**
   * The data needed to create a BanDetails.
   */
  data: Prisma.XOR<Prisma.BanDetailsCreateInput, Prisma.BanDetailsUncheckedCreateInput>
}

/**
 * BanDetails createMany
 */
export type BanDetailsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BanDetails.
   */
  data: Prisma.BanDetailsCreateManyInput | Prisma.BanDetailsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BanDetails createManyAndReturn
 */
export type BanDetailsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BanDetails
   */
  select?: Prisma.BanDetailsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BanDetails
   */
  omit?: Prisma.BanDetailsOmit<ExtArgs> | null
  /**
   * The data used to create many BanDetails.
   */
  data: Prisma.BanDetailsCreateManyInput | Prisma.BanDetailsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BanDetailsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BanDetails update
 */
export type BanDetailsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BanDetails
   */
  select?: Prisma.BanDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BanDetails
   */
  omit?: Prisma.BanDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BanDetailsInclude<ExtArgs> | null
  /**
   * The data needed to update a BanDetails.
   */
  data: Prisma.XOR<Prisma.BanDetailsUpdateInput, Prisma.BanDetailsUncheckedUpdateInput>
  /**
   * Choose, which BanDetails to update.
   */
  where: Prisma.BanDetailsWhereUniqueInput
}

/**
 * BanDetails updateMany
 */
export type BanDetailsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BanDetails.
   */
  data: Prisma.XOR<Prisma.BanDetailsUpdateManyMutationInput, Prisma.BanDetailsUncheckedUpdateManyInput>
  /**
   * Filter which BanDetails to update
   */
  where?: Prisma.BanDetailsWhereInput
  /**
   * Limit how many BanDetails to update.
   */
  limit?: number
}

/**
 * BanDetails updateManyAndReturn
 */
export type BanDetailsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BanDetails
   */
  select?: Prisma.BanDetailsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BanDetails
   */
  omit?: Prisma.BanDetailsOmit<ExtArgs> | null
  /**
   * The data used to update BanDetails.
   */
  data: Prisma.XOR<Prisma.BanDetailsUpdateManyMutationInput, Prisma.BanDetailsUncheckedUpdateManyInput>
  /**
   * Filter which BanDetails to update
   */
  where?: Prisma.BanDetailsWhereInput
  /**
   * Limit how many BanDetails to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BanDetailsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BanDetails upsert
 */
export type BanDetailsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BanDetails
   */
  select?: Prisma.BanDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BanDetails
   */
  omit?: Prisma.BanDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BanDetailsInclude<ExtArgs> | null
  /**
   * The filter to search for the BanDetails to update in case it exists.
   */
  where: Prisma.BanDetailsWhereUniqueInput
  /**
   * In case the BanDetails found by the `where` argument doesn't exist, create a new BanDetails with this data.
   */
  create: Prisma.XOR<Prisma.BanDetailsCreateInput, Prisma.BanDetailsUncheckedCreateInput>
  /**
   * In case the BanDetails was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BanDetailsUpdateInput, Prisma.BanDetailsUncheckedUpdateInput>
}

/**
 * BanDetails delete
 */
export type BanDetailsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BanDetails
   */
  select?: Prisma.BanDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BanDetails
   */
  omit?: Prisma.BanDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BanDetailsInclude<ExtArgs> | null
  /**
   * Filter which BanDetails to delete.
   */
  where: Prisma.BanDetailsWhereUniqueInput
}

/**
 * BanDetails deleteMany
 */
export type BanDetailsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BanDetails to delete
   */
  where?: Prisma.BanDetailsWhereInput
  /**
   * Limit how many BanDetails to delete.
   */
  limit?: number
}

/**
 * BanDetails without action
 */
export type BanDetailsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BanDetails
   */
  select?: Prisma.BanDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BanDetails
   */
  omit?: Prisma.BanDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BanDetailsInclude<ExtArgs> | null
}
