// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { StatusResponse, User } from "./user";

export const protobufPackage = "auth.v1";

/** Message for sign up request */
export interface SignUpRequest {
  name?: string | null | undefined;
  email: string;
  password: string;
  phoneNumber?: string | null | undefined;
}

/** Message for sign in request */
export interface SignInRequest {
  email: string;
  password: string;
}

/** Message for sigh in / verify email response containing tokens */
export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
  user: User | null;
}

/** Message for refresh tokens response */
export interface RefreshTokensResponse {
  accessToken: string;
  refreshToken: string;
}

/** Message representing a token */
export interface Token {
  token: string;
}

/** Message representing an email */
export interface Email {
  email: string;
}

/** Message for setting a new password */
export interface SetNewPasswordRequest {
  token: string;
  password: string;
}

export const AUTH_V1_PACKAGE_NAME = "auth.v1";

/** AuthService defines the gRPC service for authentication. */

export interface AuthServiceClient {
  /** rpc to sign up a user */

  signUp(request: SignUpRequest): Observable<User>;

  /** rpc to sign in a user */

  signIn(request: SignInRequest): Observable<AuthResponse>;

  /** rpc to verify email */

  verifyEmail(request: Token): Observable<AuthResponse>;

  /** rpc to refresh tokens */

  refreshTokens(request: Token): Observable<RefreshTokensResponse>;

  /** rpc to resend confirmation email */

  resendEmail(request: Email): Observable<StatusResponse>;

  /** rpc to reset password */

  initResetPassword(request: Email): Observable<StatusResponse>;

  /** rpc to set new password */

  setNewPassword(request: SetNewPasswordRequest): Observable<StatusResponse>;
}

/** AuthService defines the gRPC service for authentication. */

export interface AuthServiceController {
  /** rpc to sign up a user */

  signUp(request: SignUpRequest): Promise<User> | Observable<User> | User;

  /** rpc to sign in a user */

  signIn(request: SignInRequest): Promise<AuthResponse> | Observable<AuthResponse> | AuthResponse;

  /** rpc to verify email */

  verifyEmail(request: Token): Promise<AuthResponse> | Observable<AuthResponse> | AuthResponse;

  /** rpc to refresh tokens */

  refreshTokens(
    request: Token,
  ): Promise<RefreshTokensResponse> | Observable<RefreshTokensResponse> | RefreshTokensResponse;

  /** rpc to resend confirmation email */

  resendEmail(request: Email): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to reset password */

  initResetPassword(request: Email): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to set new password */

  setNewPassword(request: SetNewPasswordRequest): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "signUp",
      "signIn",
      "verifyEmail",
      "refreshTokens",
      "resendEmail",
      "initResetPassword",
      "setNewPassword",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
