// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Email, StatusResponse, User } from "./user";

export const protobufPackage = "auth.v1";

/** Message for sign up request */
export interface SignUpRequest {
  name: string;
  email: string;
  password: string;
  phoneNumber?: string | null | undefined;
}

/** Message for sign in request */
export interface SignInRequest {
  email: string;
  password: string;
}

/** Message representing a token */
export interface Token {
  token: string;
}

/** Message for setting a new password */
export interface SetNewPasswordRequest {
  token: string;
  password: string;
}

export const AUTH_V1_PACKAGE_NAME = "auth.v1";

/** AuthService defines the gRPC service for authentication. */

export interface AuthServiceClient {
  /** rpc to sign up a user */

  signUp(request: SignUpRequest): Observable<User>;

  /** rpc to sign in a user */

  signIn(request: SignInRequest): Observable<User>;

  /** rpc to confirm email */

  confirmEmail(request: Token): Observable<StatusResponse>;

  /** rpc to resend confirmation email */

  resendEmail(request: Email): Observable<StatusResponse>;

  /** rpc to reset password */

  resetPassword(request: Email): Observable<StatusResponse>;

  /** rpc to set new password */

  setNewPassword(request: SetNewPasswordRequest): Observable<StatusResponse>;
}

/** AuthService defines the gRPC service for authentication. */

export interface AuthServiceController {
  /** rpc to sign up a user */

  signUp(request: SignUpRequest): Promise<User> | Observable<User> | User;

  /** rpc to sign in a user */

  signIn(request: SignInRequest): Promise<User> | Observable<User> | User;

  /** rpc to confirm email */

  confirmEmail(request: Token): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to resend confirmation email */

  resendEmail(request: Email): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to reset password */

  resetPassword(request: Email): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to set new password */

  setNewPassword(request: SetNewPasswordRequest): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "signUp",
      "signIn",
      "confirmEmail",
      "resendEmail",
      "resetPassword",
      "setNewPassword",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
