// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: health-check.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "health_check.v1";

/** HealthCheckResponse represents the health status response. */
export interface HealthCheckResponse {
  serving: boolean;
  message: string;
}

export const HEALTH_CHECK_V1_PACKAGE_NAME = "health_check.v1";

/** HealthCheckService defines the gRPC service for health checking. */

export interface HealthCheckServiceClient {
  /** rpc to check the health status of the service */

  checkAppHealth(request: Empty): Observable<HealthCheckResponse>;

  /** rpc to check database connectivity */

  checkDatabaseConnection(request: Empty): Observable<HealthCheckResponse>;
}

/** HealthCheckService defines the gRPC service for health checking. */

export interface HealthCheckServiceController {
  /** rpc to check the health status of the service */

  checkAppHealth(request: Empty): Promise<HealthCheckResponse> | Observable<HealthCheckResponse> | HealthCheckResponse;

  /** rpc to check database connectivity */

  checkDatabaseConnection(
    request: Empty,
  ): Promise<HealthCheckResponse> | Observable<HealthCheckResponse> | HealthCheckResponse;
}

export function HealthCheckServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["checkAppHealth", "checkDatabaseConnection"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("HealthCheckService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("HealthCheckService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const HEALTH_CHECK_SERVICE_NAME = "HealthCheckService";
