// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";

export const protobufPackage = "user.v1";

/** declaration of User message */
export interface User {
  id: string;
  name?: string | null | undefined;
  email: string;
  phoneNumber?: string | null | undefined;
  role: string;
  avatarUrl?: string | null | undefined;
  passwordHash: string;
  isEmailVerified: boolean;
  lastLogin?: Date | null | undefined;
  isBanned: boolean;
  banReason?: string | null | undefined;
  bannedAt?: Date | null | undefined;
  refreshTokenHash?: string | null | undefined;
  createdAt: Date | null;
  updatedAt: Date | null;
}

/** declaration of Id message */
export interface Id {
  id: string;
}

/** declaration of Email message */
export interface Email {
  email: string;
}

/** Message representing a status response */
export interface StatusResponse {
  success: boolean;
  message: string;
}

/** Message for creating a new user */
export interface CreateUserRequest {
  email: string;
  passwordHash: string;
  name?: string | null | undefined;
  phoneNumber?: string | null | undefined;
  avatarUrl?: string | null | undefined;
}

/** Message for updating an existing user */
export interface UpdateUserRequest {
  id: string;
  name?: string | null | undefined;
  phoneNumber?: string | null | undefined;
  avatarUrl?: string | null | undefined;
}

/** Message for banning a user */
export interface BanUserRequest {
  id: string;
  reason?: string | null | undefined;
}

/** Message for password related requests */
export interface PasswordRequest {
  id: string;
  password: string;
}

export const USER_V1_PACKAGE_NAME = "user.v1";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

/** UserService defines the gRPC service for managing users. */

export interface UserServiceClient {
  /** rpc to get user by email */

  getUserByEmail(request: Email): Observable<User>;

  /** rpc to get user by id */

  getUserById(request: Id): Observable<User>;

  /** rpc to create a new user */

  createUser(request: CreateUserRequest): Observable<User>;

  /** rpc to update an existing user */

  updateUser(request: UpdateUserRequest): Observable<User>;

  /** rpc to delete a user by id */

  deleteUser(request: Id): Observable<StatusResponse>;

  /** rpc to ban a user by id */

  banUser(request: BanUserRequest): Observable<User>;

  /** rpc to unban a user by id */

  unbanUser(request: Id): Observable<User>;

  /** rpc to confirm user password */

  confirmPassword(request: PasswordRequest): Observable<StatusResponse>;

  /** rpc to change user password */

  changePassword(request: PasswordRequest): Observable<StatusResponse>;
}

/** UserService defines the gRPC service for managing users. */

export interface UserServiceController {
  /** rpc to get user by email */

  getUserByEmail(request: Email): Promise<User> | Observable<User> | User;

  /** rpc to get user by id */

  getUserById(request: Id): Promise<User> | Observable<User> | User;

  /** rpc to create a new user */

  createUser(request: CreateUserRequest): Promise<User> | Observable<User> | User;

  /** rpc to update an existing user */

  updateUser(request: UpdateUserRequest): Promise<User> | Observable<User> | User;

  /** rpc to delete a user by id */

  deleteUser(request: Id): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to ban a user by id */

  banUser(request: BanUserRequest): Promise<User> | Observable<User> | User;

  /** rpc to unban a user by id */

  unbanUser(request: Id): Promise<User> | Observable<User> | User;

  /** rpc to confirm user password */

  confirmPassword(request: PasswordRequest): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to change user password */

  changePassword(request: PasswordRequest): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getUserByEmail",
      "getUserById",
      "createUser",
      "updateUser",
      "deleteUser",
      "banUser",
      "unbanUser",
      "confirmPassword",
      "changePassword",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
