// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "user.v1";

/** user roles enumeration */
export enum UserRole {
  USER = 0,
  ADMIN = 1,
  MODERATOR = 2,
  VISITOR = 3,
  UNRECOGNIZED = -1,
}

/** declaration of User message */
export interface User {
  id: string;
  name?: string | null | undefined;
  email: string;
  phoneNumber?: string | null | undefined;
  role: UserRole;
  avatarUrl?: string | null | undefined;
  passwordHash: string;
  isEmailVerified: boolean;
  lastLogin?: Date | null | undefined;
  isBanned: boolean;
  createdAt: Date | null;
  updatedAt: Date | null;
}

/** declaration of Id message */
export interface Id {
  id: string;
}

/** Message representing a status response */
export interface StatusResponse {
  success: boolean;
  message: string;
}

/** Message for updating an existing user */
export interface UpdateUserRequest {
  id: string;
  name?: string | null | undefined;
  phoneNumber?: string | null | undefined;
  avatarUrl?: string | null | undefined;
}

/** Message for banning a user */
export interface BanUserRequest {
  id: string;
  bannedBy: string;
  reason?: string | null | undefined;
  banUntil?: Date | null | undefined;
}

/** Message for ban details */
export interface BanDetails {
  id: string;
  userId: string;
  isBanned: boolean;
  bannedBy: string;
  banReason?: string | null | undefined;
  banUntil?: Date | null | undefined;
  createdAt: Date | null;
}

/** Message for ban details response */
export interface BanDetailsResponse {
  banDetails: BanDetails[];
}

/** Message for getting banned users response */
export interface GetBannedUsersResponse {
  users: User[];
}

/** Message for password related requests */
export interface PasswordRequest {
  id: string;
  password: string;
}

/** Message for changing user role */
export interface UserRoleRequest {
  id: string;
  role: UserRole;
}

export const USER_V1_PACKAGE_NAME = "user.v1";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

/** UserService defines the gRPC service for managing users. */

export interface UserServiceClient {
  /**
   * --- user access rpc methods ---
   * rpc to get user by id
   */

  getUserById(request: Id): Observable<User>;

  /** rpc to update an existing user */

  updateUser(request: UpdateUserRequest): Observable<User>;

  /** rpc to delete a user by id */

  deleteUser(request: Id): Observable<StatusResponse>;

  /** rpc to confirm user password */

  confirmPassword(request: PasswordRequest): Observable<StatusResponse>;

  /** rpc to change user password */

  changePassword(request: PasswordRequest): Observable<StatusResponse>;

  /**
   * --- admin access rpc methods ---
   * rpc to ban a user by id
   */

  banUser(request: BanUserRequest): Observable<User>;

  /** rpc to unban a user by id */

  unbanUser(request: BanUserRequest): Observable<User>;

  /** rpc to get all banned users */

  getBannedUsers(request: Empty): Observable<GetBannedUsersResponse>;

  /** get ban details by user id */

  getBanDetailsByUserId(request: Id): Observable<BanDetailsResponse>;

  /** rpc to change user role */

  changeUserRole(request: UserRoleRequest): Observable<User>;
}

/** UserService defines the gRPC service for managing users. */

export interface UserServiceController {
  /**
   * --- user access rpc methods ---
   * rpc to get user by id
   */

  getUserById(request: Id): Promise<User> | Observable<User> | User;

  /** rpc to update an existing user */

  updateUser(request: UpdateUserRequest): Promise<User> | Observable<User> | User;

  /** rpc to delete a user by id */

  deleteUser(request: Id): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to confirm user password */

  confirmPassword(request: PasswordRequest): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /** rpc to change user password */

  changePassword(request: PasswordRequest): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;

  /**
   * --- admin access rpc methods ---
   * rpc to ban a user by id
   */

  banUser(request: BanUserRequest): Promise<User> | Observable<User> | User;

  /** rpc to unban a user by id */

  unbanUser(request: BanUserRequest): Promise<User> | Observable<User> | User;

  /** rpc to get all banned users */

  getBannedUsers(
    request: Empty,
  ): Promise<GetBannedUsersResponse> | Observable<GetBannedUsersResponse> | GetBannedUsersResponse;

  /** get ban details by user id */

  getBanDetailsByUserId(request: Id): Promise<BanDetailsResponse> | Observable<BanDetailsResponse> | BanDetailsResponse;

  /** rpc to change user role */

  changeUserRole(request: UserRoleRequest): Promise<User> | Observable<User> | User;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getUserById",
      "updateUser",
      "deleteUser",
      "confirmPassword",
      "changePassword",
      "banUser",
      "unbanUser",
      "getBannedUsers",
      "getBanDetailsByUserId",
      "changeUserRole",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
